### PR TITLE
Fix bad commit 5b4b076. Closes #19

### LINKED ISSUE #19: No auto-rejoin to channels on reconnec №2 | broken
In continuation of previous issue it seems my commit broke Kaguya.
It seems I totally forgot that https://github.com/Luminarys/Kaguya/blob/master/lib/kaguya/core.ex#L45 calls itself which results in a error.

### PR DESCRIPTION
**Pull request by DoumanAsh**
Move sending of user name and password back to a separate task.
Since it uses :send message to perform sending it will queued properly.

### CODE REVIEW

**Comment by Luminarys** [comment]
Seeing as this is being reverted, the channel reconnect synchronization will need to be implemented or removed.

**Comment by DoumanAsh** [comment]
No, I'm not exactly reverting it.
I just returning spawn of task that sends messages to send nick/pass.

It should not affect original commit as my initial assumption about the way nick/pass is sent

P.s. I started my bot under different name and it starts just fine now

**Comment by Luminarys** [comment]
It seems to me like it could be a potential race condition though, since the spawned Task could be scheduled after the `:rejoin_chan` completes, causing a failure.

**Comment by DoumanAsh** [comment]
Hm... yes, you're correct, Task is not guaranteed to start at all so there is chance that it might start very late,

Let me re-think it then.

**Comment by DoumanAsh** [comment]
I've reworked sending of message in a separate function and now at `:init` Kaguya will just call it directly instead of spawning task that performs call to gen server.

**Comment by Luminarys** [comment]
Looks good, thanks.

**Pull request merged**
